---
title: "Praticas em Limpeza e Tratamento de Dados"
Curso: "Ciencia de Dados"
---

## Atividade pratica

-   Tratar o conjunto de dados - tempo.csv

#### Importando os dados

```{r}
DataFrame = read.csv('tempo.csv', sep = ';')

DataFrame
```

#### Tratando os valores nulos

```{r}
summary(DataFrame$Aparencia)
summary(DataFrame$Temperatura)
summary(DataFrame$Umidade)
summary(DataFrame$Vento)
summary(DataFrame$Jogar)
```

```{r}
summary(DataFrame$Umidade)
MeanHumidity = mean(DataFrame$Umidade, na.rm = T)
DataFrame[!complete.cases(DataFrame),]
DataFrame[is.na(DataFrame$Umidade),]$Umidade = MeanHumidity

summary(DataFrame$Umidade)
```

#### Tratando valores fora do dominio

```{r}
colnames(DataFrame)

unique(DataFrame$Aparencia)
unique(DataFrame$Temperatura)
unique(DataFrame$Umidade)
unique(DataFrame$Vento)
unique(DataFrame$Jogar)
```

```{r}
unique(DataFrame$Aparencia)
table(DataFrame$Aparencia)
DataFrame[DataFrame$Aparencia == "menos", ]$Aparencia = 'chuva'

tail(DataFrame, 16)
```

#### Removendo Colunas não usadas

```{r}
DataFrame$Vento <- NULL
DataFrame = DataFrame[(DataFrame$Temperatura > -130) 
          & (DataFrame$Temperatura < 130)
          & (DataFrame$Umidade >= 0) 
          & (DataFrame$Umidade <= 100), ]

DataFrame
```
