---
title: "RLimpeza e Tratamento de Dados"
Curso: "Cientista de Dados"
---

### Importando dados, string vazias NA, string em fatores

```{r}

# Importando os dados

                            # Separador de colunas      # Definido as string como fatores
data = read.csv('Churn.csv', sep = ';', na.strings = '', stringsAsFactors = T)
head(data)
summary(data)
```

### Dando nome as colunas

```{r}
colnames(data) = c(
                    'Id',
                    'Score',
                    'Estado',
                    'Genero',
                    'Idade',
                    'Patrimonio',
                    'Saldo',
                    'Produtos',
                    'TemCartCredito',
                    'Ativo',
                    'Salario',
                    'Saiu'
)
head(data)
```

### Explorando dados e colulas categoricas

```{r}


OccurrencesofStates <- table(data$Estado)
barplot(
  OccurrencesofStates, 
  main = 'Ocorrência dos estados', 
  xlab = 'Estado',
  ylab = 'Quantidade'
)



OccurrencesofGender <- table(data$Genero)
barplot(
  OccurrencesofGender,
  main = 'Ocorrência dos Gêneros',
  xlab = 'Gênero',
  ylab = 'Quantidade'
)


```

### Exlorando dados númericos

```{r}

print('Score')
summary(data$Score)


boxplot(
  data$Score,
  main = 'Resumo do Score dos Cliente',
  ylab = 'Score'
)

hist(
  data$Score,
  main = 'Resumo do Score dos Clientes',
  xlab = 'Score',
  ylab = 'Frequência'
)



print('Idade')
summary(data$Idade)
boxplot(data$Idade)
hist(data$Idade)


print('Saldo')
summary(data$Saldo)
boxplot(data$Saldo)
hist(data$Saldo)


print('Salario')
print(data$Salario)
summary(data$Salario)
boxplot(data$Salario)
hist(data$Salario)
```

### Tratando Dados Coluna Salario

```{r}

data[!complete.cases(data),]


summary(data$Salario)

median(data$Salario, na.rm = T)

data[is.na(data$Salario),]$Salario = median(data$Salario,na.rm = T)

data[!complete.cases(data$Salario),]

summary(data$Salario)


data$Genero
```

### Tratamento de dados coluna Genero

```{r}

unique(data$Genero)
summary(data$Genero)

data[is.na(data$Genero) | data$Genero == "M", ]$Genero = "Masculino"
data[data$Genero == 'F' | data$Genero == 'Fem', ]$Genero = 'Feminino'

data$Genero = factor(data$Genero)

```

### Tratando os dados da Coluna idade

```{r}

summary(data$Idade)

median_age = median(data$Idade)
data[data$Idade < 0 | data$Idade > 110, ]$Idade = median_age

data[data$Idade <0 | data$Idade > 110,]

```

### Tratando dados duplicados

```{r}

LookingForDuplicateData = data[duplicated(data$Id), ]

LookingForDuplicateData

duplicate_id = data[data$Id == 81, ]
duplicate_id

data = data[-c(82),]

LookingForDuplicateData = data[duplicated(data$Id), ]
LookingForDuplicateData

duplicate_id = data[data$Id == 81, ]
duplicate_id

```

### Tratando dados fora do dominio

```{r }

unique(data$Estado)
summary(data$Estado)

data[!data$Estado %in% c('RS','SC','PR'),]$Estado = 'RS'
summary(data$Estado)

data$Estado = factor(data$Estado)

summary(data$Estado)
```
### Outliers
```{r}

StandardDeviation = sd(data$Salario, na.rm = T)
StandardDeviation

data[data$Salario >= 2 * StandardDeviation, ]$Salario


boxplot(data$Salario)

boxplot(data$Salario, outline = F)

boxplot(data$Salario)$out


MedianWage = median(data$Salario)
MedianWage

data[data$Salario >= 2 * StandardDeviation, ]$Salario = MedianWage
```
